name: Make Build

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6-beta
      - name: Setup NodeJs
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: yarn install
      - name: make build
        run: yarn build
        
  

